export enum MineralType {
  OBSIDIAN = 'OBSIDIAN',   // < 0.2 (Deep Despair)
  LAPIS = 'LAPIS',         // 0.2 - 0.4 (Melancholy/Thought)
  MOONSTONE = 'MOONSTONE', // 0.4 - 0.6 (Peace/Calm)
  CITRINE = 'CITRINE',     // 0.6 - 0.8 (Joy)
  GOLD = 'GOLD',           // > 0.8 (Euphoria)
  // Legacy support if needed, map SANDSTONE to MOONSTONE logic or keep distinct
  SANDSTONE = 'SANDSTONE' 
}

export enum SurfaceState {
  BARREN = 'BARREN',
  FLOWER = 'FLOWER',
  HOUSE = 'HOUSE',
}

export interface GemWisdom {
  mineralName: string;
  composition: string; // e.g., "70% Serenity, 30% Melancholy"
  quote: string;       // Representative sentence from diary
  advice: string;
}

export interface Entry {
  id: string;
  date: string; // ISO String
  content: string;
  moodScore: number; // 0 to 1
  thickness: number; // pixels
  mineralType: MineralType;
  hasGem: boolean;
  gemWisdom?: GemWisdom; // Generated by Gemini
}

export interface Particle {
  id: number;
  x: number;
  y: number;
  color: string;
  speed: number;
  size: number;
}
